### PR TITLE
Review Title, Description, License and Vignette 

### PR DESCRIPTION
**Pull request by mianzg**
@larnsce 
I started to prepare the first release for CRAN. I would like to agree on the DESCRIPTION file and have a review on the vignette.

### CODE REVIEW

**Comment by larnsce** [comment]
Thank you, @mianzg. My comments:

## DESCRIPTION

- Title: R data package development tools for openwashdata
- License: Consider: https://choosealicense.com/licenses/unlicense/ or https://firstdonoharm.dev/version/2/0/license/
- Imports: Try do reduce the dependencies a bit (e.g. do you need `fs`, or can you replace it with function from base R?). Do you interact with GitHub, is `gh` needed? Can you replace `readr`?
- URL: points to the wrong organisation
- Description: The sentence ends with and etc. Try to end this sentence without etc. 

It provides templates to reduce manual editing for tidy data exporting, README writing, pkgdown configuration and content.

## Vignette

- Instead of numbering sections manually, you can define in the YAML header for section numbers to be shown in the output.

> Once you initialize an R package named with `fssample` with `devtools`

The step of initializing fssample with devtools needs to be documented first.

> After executing the last a few lines in `data-processing.R`, namely,

Revise this sentence. It's difficult to understand.

> Go to `R/` and fill in the title and description for the dataset.

This needs more information.

> Communicate dataset

This section is not complete. It needs to be split into several steps that explain in more detail what the user is supposed to do.

**Comment by mianzg** [comment]
@larnsce 
Title, URL, and Description are modified.

Should we exclude "Communicate dataset" in the get-started vignette?

**Comment by larnsce** [comment]
No, keep that section. It's the most valuable part from an outsider data curation perspective.

**Comment by mianzg** [comment]
I started a new branch called "cran" to continue working on it. I need the new branch so I can remove the code comments, but I want to keep those comments in the dev branch. They are mostly for feature improvement that I hope to implement in next version. I will merge and close this pull request.

**Pull request merged**
